theme: jekyll-theme-cayman
name: Sherlock Holmes and the Philosophical Stone
title: "Sherlock Holmes and the Philosophical Stone"
description: A new short story of Sherlock Holmes and Dr. Watson 
url: "https://mariapalomares.github.io/year3-story-2018/"
