theme: jekyll-theme-cayman
name: Sherlock Holmes and the Philosophical Stone
title: "Sherlock Holmes and the Philosophical Stone"
description: A new story of Sherlock Holmes and Doctor Watson 
url: "https://mariapalomares.github.io/year3-story-2018/"
